### ISSUE TITLE
Doesn't compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by winks** [jedisct1/dsvpn#22]
FYI: Doesn't build on this amd64 Ubuntu 14.04 VPS (EOL April 2022, not 2019 it seems)

I don't expect a fix but maybe worth mentioning some sort of minimal whatever it is... Kernel version probably?

```
% make
cc -march=native -Ofast -Wall -W -Wshadow -Wmissing-prototypes  -Iinclude -o dsvpn src/vpn.c src/charm.c src/os.c
src/charm.c: In function ‘uc_randombytes_buf’:
src/charm.c:329:26: error: ‘SYS_getrandom’ undeclared (first use in this function)
     if ((size_t) syscall(SYS_getrandom, buf, (int) len, 0) != len) {
                          ^
src/charm.c:329:26: note: each undeclared identifier is reported only once for each function it appears in
make: *** [dsvpn] Error 1
```

```
% uname -a
Linux xyz 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

**Comment by jedisct1** [comment]
That C library seems to be really old.

You can try replacing `SYS_getrandom` with `318`, but maybe the kernel doesn't have that interface either.

Looks like this interface was introduced in 2014. This is a long time ago so I don't remember what exact kernel version it was.

**Comment by winks** [comment]
Yes, using `318` works. thanks!

Also it seems to be Linux kernel 3.4.17+.

Source: https://lwn.net/Articles/711013/ + https://github.com/boostorg/uuid/issues/92

No time to test functionality right now, but it builds and starts.

```
(florian@cordelia ~/code/dsvpn) (git)-[master] % sudo ./dsvpn server vpn.key auto 1959
Interface: [tun0]
net.ipv4.ip_forward = 1
RTNETLINK answers: Invalid argument
Listening to *:1959
```
(the RTNETLINK might be because this openvz or some other weird virt stuff, but I'm not sure)

**Comment by jedisct1** [comment]
The `RTNETLINK` message can safely be ignored. It is just trying to remove previous rules, in case of a network change after an unclean shutdown.

**Comment by clarus** [comment]
It works, thanks!
